# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-30 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_productpurchase_productpurchasemanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpurchase',
            name='order_id',
            field=models.CharField(default='abc123', max_length=120),
            preserve_default=False,
        ),
    ]
