# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-30 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_productpurchase_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpurchase',
            name='user',
        ),
    ]
